// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6srIOlVtJgOrJxopqe4QcrdjfG5PDxbs',
    appId: '1:287923673174:web:1642a9da67892aec4d83f7',
    messagingSenderId: '287923673174',
    projectId: 'habit-tracker-e5287',
    authDomain: 'habit-tracker-e5287.firebaseapp.com',
    storageBucket: 'habit-tracker-e5287.appspot.com',
    measurementId: 'G-X1L23H6TXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZcPCa04NY5wPSpGUWUco6vZagxyU2T0',
    appId: '1:287923673174:android:b7eae932ae03dc6c4d83f7',
    messagingSenderId: '287923673174',
    projectId: 'habit-tracker-e5287',
    storageBucket: 'habit-tracker-e5287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHU7nU0jnos1_ot6GftjV4v6Ip0ggm9aA',
    appId: '1:287923673174:ios:a0ed8df0b0d4512b4d83f7',
    messagingSenderId: '287923673174',
    projectId: 'habit-tracker-e5287',
    storageBucket: 'habit-tracker-e5287.appspot.com',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHU7nU0jnos1_ot6GftjV4v6Ip0ggm9aA',
    appId: '1:287923673174:ios:a0ed8df0b0d4512b4d83f7',
    messagingSenderId: '287923673174',
    projectId: 'habit-tracker-e5287',
    storageBucket: 'habit-tracker-e5287.appspot.com',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6srIOlVtJgOrJxopqe4QcrdjfG5PDxbs',
    appId: '1:287923673174:web:859a8478307db5664d83f7',
    messagingSenderId: '287923673174',
    projectId: 'habit-tracker-e5287',
    authDomain: 'habit-tracker-e5287.firebaseapp.com',
    storageBucket: 'habit-tracker-e5287.appspot.com',
    measurementId: 'G-TF78W2E6NZ',
  );
}
